### PR TITLE
rename HTTPHandler to ServeHTTP (for compatibility with other packages)

### PR DESCRIPTION
**Pull request by frederikhors**
@purehyperbole, can you please give me an ETA for the merge and release?

### CODE REVIEW

**Comment by purehyperbole** [comment]
Hi @frederikhors 

Thanks for raising the PR!

`HTTPHandler` is intended to be used with a mux or router, rather than handle all http requests. 

This also changes the public interface of the library which generally we generally try to avoid without a good reason. 

Could you please provide an example of why you need this to be renamed? Thanks!

**Comment by codewinch** [comment]
Those are two different things. You can't just rename them. :)

**Comment by codewinch** [comment]
@frederikhors Here's a nice doc on the HTTPHandler pattern: https://medium.com/@matryer/the-http-handler-wrapper-technique-in-golang-updated-bc7fbcffa702

**Comment by frederikhors** [comment]
One example is using this code:

```go
bunrouter.HTTPHandler(sseServer)
```

instead of:

```go
func newSSEHandler(sseServer *sse.Server) bunrouter.HandlerFunc {
	return func(w http.ResponseWriter, r bunrouter.Request) error {
		sseServer.HTTPHandler(w, r.Request)

		return nil
	}
}
```

I'm using https://github.com/uptrace/bunrouter.

**Comment by frederikhors** [comment]
And many others like this.

**Comment by codewinch** [comment]
Think this might be a good idea, even though normally I would be against changing the public API as well.

It matches how https://github.com/alexandrevicenzi/go-sse/blob/master/sse.go#L49 and https://github.com/julienschmidt/sse/blob/master/sse.go#L229 do it, and a lot of mux/routers expect to work this way.

**Comment by purehyperbole** [comment]
@frederikhors @codewinch thanks for the feedback. 

I'll merge this and create a new release.

**Review by purehyperbole — APPROVED** [review]

**Pull request merged**
